apiVersion: v1
kind: ConfigMap
metadata:
  name: dingding-config
  namespace: monitoring
data:
  config.yml: |
    targets:
      webhook1:
        url: https://oapi.dingtalk.com/robot/send?access_token=437872486374280d187e0b6f2461894573ac901cd043d1991e77f346babd4c75 
