apiVersion: apps/v1
kind: Deployment
metadata:
  name: dingding
  namespace: monitoring
  labels:
    app: dingding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dingding
  template:
    metadata:
      labels:
        app: dingding
    spec:
      containers:
      - name: dingding
        image: timonwong/prometheus-webhook-dingtalk:v2.0.0
        ports:
        - containerPort: 8060
        volumeMounts:
        - name: config
          mountPath: "/etc/prometheus-webhook-dingtalk"
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: dingding-config
          items:
          - key: "config.yml"
            path: "config.yml"
